### ISSUE TITLE
Floodguard can be bypassed using OOC commands

### ISSUE THREAD

**Issue by axestyra** [Crystalwarrior/KFO-Server#130]
Using commands such as /g or /need to spam out of character chat is not stopped by the OOC floodguard. I've had to add the mod_only decorator for these commands to prevent said commands from being spammed. Also, I heard that a solution to this may already exist as Vanilla's ModBot somewhat prevents this.

**Comment by stonedDiscord** [comment]
this has been solved in my fork
https://github.com/stonedDiscord/KFO-Server/commit/fa3392d6c895d34a13a513c484425a70c3a7f5bc
also no one needs to switch areas multiple times a second

**Comment by Crystalwarrior** [comment]
> this has been solved in my fork [stonedDiscord@fa3392d](https://github.com/stonedDiscord/KFO-Server/commit/fa3392d6c895d34a13a513c484425a70c3a7f5bc)

Can you make a pr?

> also no one needs to switch areas multiple times a second

you're arguing said "no one" right now

**Comment by axestyra** [comment]
> this has been solved in my fork [stonedDiscord@fa3392d](https://github.com/stonedDiscord/KFO-Server/commit/fa3392d6c895d34a13a513c484425a70c3a7f5bc) also no one needs to switch areas multiple times a second

Not entirely sure if this would fix the issue raised considering this was already part of the aoprotocol when the OOC commands were being spammed. Normal OOC messages will be restricted by the floodguard but when you send a command instead it is ignored by the floodguard. This is especially an issue for commands that return non-ephemeral messages.

**Comment by axestyra** [comment]
Seeing as I am unable to replicate the OOC spam imaged above from a month ago, I'll close this issue for now.
