### ISSUE TITLE
Toggling on ''/toggle_passing_IC'' and changing area kicks you out of the server.

### ISSUE THREAD

**Issue by Chibiange** [Crystalwarrior/KFO-Server#56]
Self-explanation and a recent issue I have with the KFO server update x:. Toggling on the IC autopass kicks me out of the server unless I am a GM of it. 

Using the /sneak command doesn't kick me out however.

**Comment by Crystalwarrior** [comment]
Should be fixed by https://github.com/Crystalwarrior/KFO-Server/commit/735ff74c2e7bd17e4d30136080b02c1bd2769bdd

**Comment by Chibiange** [comment]
It's still kick me out of the server x:

**Comment by Crystalwarrior** [comment]
Fully fixed by https://github.com/Crystalwarrior/KFO-Server/commit/27dc00dca68a6f0b73589c99eaf03a13abfc72b3 😳

**Comment by Chibiange** [comment]
Can confirm, no longer get kicked, Huzzah! \o/
