### ISSUE TITLE
Players are disconnected on join.

### ISSUE THREAD

**Issue by EricPlus24** [Crystalwarrior/KFO-Server#6]
Traceback:

```
"[...]server\database.py", line 402 in _subtype_atom
   '''), (event_subtype_))
sqlite3.OperationErorr: no such table: area_event_types
```

This is on a fresh install with the last commit being [86f1713](https://github.com/Crystalwarrior/KFO-Server/commit/86f17133af104f8e6ddd91d3a8fbf0a74f071bd4) .

This doesn't occur on the official Killing Fever Online server, but occurs on a fresh install.

**Comment by Crystalwarrior** [comment]
Aw Fuck.
I wanted to rename all instances of "room" to "area" because "room" is fucking stupid but I guess I can't do that with SQL database easily.
