### ISSUE TITLE
Server shows as offline on clients older than 2.9

### ISSUE THREAD

**Issue by Ace-Lucario** [Crystalwarrior/KFO-Server#64]
My friend and I collectively tested the 2.6, 2.8, 2.8.5 , 2.9 and 2.9.1 AO clients and were only able to connect to the server on 2.9 and 2.9.1. It simply shows as offline for everything else, both on the local IP and the public one. It's unclear what could be causing it because I don't know much about python.

**Comment by Salanto** [comment]
Someone should close this issue, smh.
